openapi: 3.0.0
info:
  title: XecoFlow API Gateway
  version: 1.0.0

servers:
  - url: https://xecoflow.onrender.com/api/v1

paths:
  /payments/stkpush:
    $ref: './paths/stkpush.yaml'
  /auth/token:
    $ref: './paths/auth.yaml'
  /payments/status/{checkoutId}:
    $ref: './paths/status.yaml'